# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a4721bb93aa6bae8ffa86df24261e8c282ca617622c5b138bccadd576838836da368da730c6187926ebf55da35f4c1e3c55d2632990501f8061afc213182ea5

test:
  secret_key_base: ece7ed879202dcae2983aa55917a21b65eddd62e1a173dd69f8d2e01e44d31d93bc81e62fd20cb0f938c7006f4a19b5114bf79bbe860fe67a018b82ad9ad44e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
